# Generated by Django 3.2.6 on 2021-08-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('useremail', models.EmailField(max_length=254)),
                ('userpassword', models.CharField(max_length=200)),
                ('userimage', models.ImageField(default='/user-profiles/default.png', upload_to='user-profiles')),
                ('usermobilenumber', models.CharField(blank=True, max_length=200)),
                ('userdob', models.DateField(default='2019-08-19')),
            ],
        ),
    ]
