# Generated by Django 3.2.6 on 2021-08-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='userdob',
            field=models.DateField(default='19-12-2021'),
        ),
    ]
