# Generated by Django 3.2.6 on 2021-08-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_alter_userregister_userdob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='userimage',
            field=models.ImageField(blank=True, default='/user-profiles/default.png', upload_to='user-profiles'),
        ),
    ]
