# Generated by Django 3.2.6 on 2021-08-18 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auth', '0003_alter_userregister_userimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('task_name', models.CharField(max_length=200)),
                ('task_details', models.TextField()),
                ('task_created_date', models.DateField(auto_now_add=True)),
                ('test_created_time', models.TimeField(auto_now_add=True)),
                ('task_end_date', models.DateField()),
                ('task_end_time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.userregister')),
            ],
        ),
    ]
