# Generated by Django 3.2.6 on 2021-08-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_taskdata_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdata',
            name='task_due_date_color_data',
            field=models.CharField(default='black', max_length=200),
        ),
    ]
